name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm / registry setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          scope: "@imenesesl"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
      - name: npm try to publish the package if it's a new version
        continue-on-error: true
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
